version: "3"

services:
  api:
    restart: always
    build: ./api
    ports:
      - "5555:5555"
    depends_on:
      - mysql
  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql
  frontend:
    restart: always
    build: ./frontend
    ports:
      - "8954:8954"
  adminer:
    restart: always
    image: adminer
    ports:
      - "8080:8080"
volumes:
  mysql_data:
